name: CI/CD Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, bcmath, pdo, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run Laravel tests
        run: php artisan test

  deploy:
    name: Continuous Deployment
    needs: ci
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'


      - name: Install production dependencies
        run: |
          composer install \
          --no-dev \
          --no-interaction \
          --prefer-dist \
          --optimize-autoloader


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'


      - name: Build assets
        run: |
          npm ci
          npm run build


      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          server_port: 22
          local_path: './'
          remote_path: ${{ secrets.HOSTINGER_PATH }}

